---
title: "DD Double ML"
output: html_document
date: "2022-12-15"
---

```{r Data Preparation}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol',
      'distress_score_di_1y', 'distress_score_pd_1y', 
      'distress_score_di_2y', 'distress_score_pd_2y')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))
data_raw = data

#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(65:463)]<-scale(data.frame(data[, c(65:463)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(465:1443)]<-scale(data.frame(data[, c(465:1443)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y",
       'distress_score_di_1y', 'distress_score_pd_1y', 
       'distress_score_di_2y', 'distress_score_pd_2y')

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


```




```{r Double ML}

###############################################Double ML#############################################

library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(lmtest)
library(sandwich)
library(ggplot2)

# Load required packages for this tutorial
# remotes::install_github("DoubleML/doubleml-for-r")
library(DoubleML)
library(mlr3)
library(mlr3learners)
library(data.table)
library(ggplot2)



######################### Ensemble Learner ############################
#install.packages('mlr3pipelines')
#install.packages('mlr3verse')
#install.packages('kknn')

library(kknn)
library(paradox)
library(mlr3pipelines)
library(mlr3verse)
library(mlr3learners)


graph_ensemble = po("branch", c("lasso", "forest", "xgboost", "svm", "knn")) %>>%
  gunion(list(
    po("learner", lrn("regr.cv_glmnet", s='lambda.min')),
    po("learner", lrn("regr.ranger", num.trees = 20000)),
    po("learner", lrn("regr.xgboost", objective = "reg:squarederror")),
    po("learner", lrn("regr.svm", kernel = 'radial')),
    po("learner", lrn("regr.kknn"))
  )) %>>%
  po("unbranch", c("lasso", "forest", "xgboost", "svm", "knn")) %>>%
  po("regravg", 5)


# For regression (nuisance parts with continuous outcome)
graph_ensemble_regr = gunion(list(
  po("learner", lrn("regr.cv_glmnet", s='lambda.min')),
  po("learner", lrn("regr.ranger", num.trees = 20000)),
  po("learner", lrn("regr.xgboost", objective = "reg:squarederror")),
  po("learner", lrn("regr.svm", kernel = 'radial')),
  po("learner", lrn("regr.kknn"))
)) %>>%
  po("regravg", 5)

# Class of ' graph_ensemble'
class(graph_ensemble_regr)

# Plot the graph
graph_ensemble_regr$plot()



# For classification (nuisance part ml_m in the Bonus example)
graph_ensemble_classif = gunion(list(
  po("learner", lrn("classif.cv_glmnet", s='lambda.min')),
  po("learner", lrn("classif.ranger", num.trees = 20000)),
  po("learner", lrn("classif.xgboost", objective = "binary:logistic", eval_metric = "logloss")),
  po("learner", lrn("classif.svm", kernel = 'radial')),
  po("learner", lrn("classif.kknn"))
)) %>>%
  po("classifavg", 5)

# Class of 'graph_ensemble'
class(graph_ensemble_classif)

# Plot the graph
graph_ensemble_classif$plot()


ensemble_pipe_regr = as_learner(graph_ensemble_regr)
ensemble_pipe_classif = as_learner(graph_ensemble_classif)


########################## Hyperparameter Tuning ###########################
library(mlr3tuning)


############## Regression Hyperparameters #################
space_regr = ps(
  # regr.cv_glmnet.alpha = p_dbl(0, 1),
  # regr.cv_glmnet.lambda = p_dbl(log(0.01), 1),
  # variance.filter.frac = p_dbl(lower = 0.25, upper = 1),
  
  regr.ranger.mtry=p_int(1, 20),
  regr.ranger.sample.fraction = p_dbl(0.5, 1),
  # regr.ranger.num.trees = p_int(500, 20000),
  
  regr.xgboost.nrounds = p_int(50,500),
  regr.xgboost.max_depth = p_int(1,10),
  regr.xgboost.eta = p_dbl(0.1, 0.5),
  regr.xgboost.lambda = p_dbl(0.1, 10),
  
  # regr.svm.degree = p_int(1,20),
  # regr.svm.cost = p_dbl(0.1, 10),
  regr.svm.gamma = p_dbl(0, 1),
  # regr.svm.kernel = p_fct(levels = c("polynomial", "radial", "sigmoid")),
  
  regr.kknn.k = p_int(1, 20)
  # regr.kknn.distance = p_int(1, 20)
)



############## Classification Hyperparameters #################
space_classif = ps(
  # classif.cv_glmnet.alpha = p_dbl(0, 1),
  # classif.cv_glmnet.lambda = p_dbl(lower = 0.05, upper = 0.1),
  # variance.filter.frac = p_dbl(lower = 0.25, upper = 1),
  
  classif.ranger.mtry = p_int(1, 20),
  classif.ranger.sample.fraction = p_dbl(0.5, 1),
  # classif.ranger.num.trees = p_int(500, 20000),
  
  classif.xgboost.nrounds = p_int(50,500),
  classif.xgboost.max_depth = p_int(1,10),
  classif.xgboost.eta = p_dbl(0.1, 0.5),
  classif.xgboost.lambda = p_dbl(0.1, 10),
  
  # classif.svm.degree = p_int(1,20),
  # classif.svm.cost = p_dbl(0.1, 10),
  classif.svm.gamma = p_dbl(0, 1),
  
  classif.kknn.k = p_int(1, 20)
  # classif.kknn.distance = p_int(1, 20)
)

```


```{r PLIV}

########################### Partially Linear IV: ADI-->DD, PLEs######################### 
library(openxlsx)


dd<-'discount_rate_1y'

ple<-c('totalscore_pps_1y', 'totalscore_pps_2y',
       'distress_score_pps_1y', 'distress_score_pps_2y',
       'distress_score_di_1y', 'distress_score_di_2y',
       'distress_score_pd_1y', 'distress_score_pd_2y')


dd_features_base<-c('age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')
              #   'cpeur2', 'eaeur1', 'iqeur2',
              #   'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              # 'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              # 'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              # 'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              # 'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              # 'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              # 'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              # 'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              # 'tfmri_ma_acmvn_b_scs_cbwmrh')

ple_features_base<-c('age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

# ple_features_base<-c('discount_rate_1y', 'age_0y', 'bmi_0y', 'income_0y', 
#                  'high_educ_0y', 'sex_0y_F', 'vol',
#                  'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
#                  'parent_identity_0y_2','parent_identity_0y_3', 
#                  'parent_identity_0y_4', 'parent_identity_0y_5',
#                  'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
#                  'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
#                  'parent_age_0y', 
#                  'cpeur2', 'eaeur1', 'iqeur2',
#                  'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
#                 'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
#               'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
#               'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
#               'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
#               'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
#               'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
#               'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
#               'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
#               'tfmri_ma_acmvn_b_scs_cbwmrh')


tune_settings = list(terminator = trm("evals", n_evals = 5),
                     algorithm = tnr("grid_search", resolution = 5),
                     rsmp_tune = rsmp("cv", folds = 5),
                     measure = list("ml_g" = msr("regr.rmse"),
                                    "ml_m" = msr("regr.rmse"),
                                    "ml_r" = msr("regr.rmse")))


#############PLIV DD########################
data_dml_base_iv = DoubleMLData$new(data,
                                      y_col = dd,
                                      d_cols = "rh_adi_perc1_0y",
                                      x_cols = dd_features_base,
                                      z_cols = "section8_0y")
data_dml_base_iv

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
dml_pliv_ensemble = DoubleMLPLIV$new(data_dml_base_iv,
                                       ml_g = ensemble_pipe_regr,
                                       ml_m = ensemble_pipe_regr,
                                       ml_r = ensemble_pipe_regr,
                                       n_folds = 5)

dml_pliv_ensemble$tune(param_set = list(
    "ml_g" = space_regr,
    "ml_m" = space_regr,
    "ml_r" = space_regr),
    tune_settings = tune_settings)

dml_pliv_ensemble$fit()
print(dml_pliv_ensemble$summary())

pliv<-as.data.frame(cbind(dml_pliv_ensemble$summary(), dml_pliv_ensemble$confint()))
write.xlsx(pliv, paste0("C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\Double ML PLIV ", dd, " Results_new.xlsx"), asTable = TRUE, rowNames=TRUE)
  

#################PLIV PLE###########################
for (y in ple) {
  data_dml_base_iv = DoubleMLData$new(data,
                                      y_col = y,
                                      d_cols = "rh_adi_perc1_0y",
                                      x_cols = ple_features_base,
                                      z_cols = "section8_0y")
  data_dml_base_iv
  
  set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
  dml_pliv_ensemble = DoubleMLPLIV$new(data_dml_base_iv,
                                       ml_g = ensemble_pipe_regr,
                                       ml_m = ensemble_pipe_regr,
                                       ml_r = ensemble_pipe_regr,
                                       n_folds = 5)
  
  dml_pliv_ensemble$tune(param_set = list(
    "ml_g" = space_regr,
    "ml_m" = space_regr,
    "ml_r" = space_regr),
    tune_settings = tune_settings)
  
  dml_pliv_ensemble$fit()
  print(dml_pliv_ensemble$summary())
  
  pliv<-as.data.frame(cbind(dml_pliv_ensemble$summary(), dml_pliv_ensemble$confint()))
  write.xlsx(pliv, paste0("C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\Double ML PLIV ", y, " Results_new.xlsx"),  asTable = TRUE, rowNames=TRUE)
  
}


# p<-c(0.00982413381266459, 0.00162609825408953, 0.000222611528966719, 0.0104945813037784, 
#      0.000601284234502506, 0.0131613887340291, 0.00390126918327938, 0.0013040799221397)


p_fdr<-as.data.frame(p.adjust(as.matrix(p), method = "fdr"))
rownames(p_fdr)<-outcomes

library(openxlsx)
write.xlsx(p_fdr, file = "C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\PLIV pval_new.xlsx", rowNames=TRUE)


```



```{r IIVM}
########################### Interactive IV: ADI-->DD, PLEs ######################### 
library(openxlsx)

dd<-'discount_rate_1y'

ple<-c('totalscore_pps_1y', 'totalscore_pps_2y',
       'distress_score_pps_1y', 'distress_score_pps_2y', 
       'distress_score_di_1y', 'distress_score_di_2y', 
       'distress_score_pd_1y', 'distress_score_pd_2y')

dd_features_base<-c('age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

ple_features_base<-c('age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')


# dd_features_base<-c('age_0y', 'bmi_0y', 'income_0y', 
#                  'high_educ_0y', 'sex_0y_F', 'vol',
#                  'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
#                  'parent_identity_0y_2','parent_identity_0y_3', 
#                  'parent_identity_0y_4', 'parent_identity_0y_5',
#                  'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
#                  'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
#                  'parent_age_0y', 
#                  'cpeur2', 'eaeur1', 'iqeur2',
#                  'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
#                 'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
#               'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
#               'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
#               'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
#               'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
#               'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
#               'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
#               'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
#               'tfmri_ma_acmvn_b_scs_cbwmrh')
# 
# ple_features_base<-c('discount_rate_1y', 'age_0y', 'bmi_0y', 'income_0y', 
#                  'high_educ_0y', 'sex_0y_F', 'vol',
#                  'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
#                  'parent_identity_0y_2','parent_identity_0y_3', 
#                  'parent_identity_0y_4', 'parent_identity_0y_5',
#                  'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
#                  'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
#                  'parent_age_0y', 
#                  'cpeur2', 'eaeur1', 'iqeur2',
#                  'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
#                 'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
#               'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
#               'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
#               'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
#               'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
#               'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
#               'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
#               'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
#               'tfmri_ma_acmvn_b_scs_cbwmrh')


tune_settings = list(terminator = trm("evals", n_evals = 10),
                     algorithm = tnr("grid_search", resolution = 10),
                     rsmp_tune = rsmp("cv", folds = 5),
                     measure = list("ml_g" = msr("regr.rmse"),
                                    "ml_m" = msr("classif.auc"),
                                    "ml_r" = msr("classif.auc")))


data_dml_base_iv = DoubleMLData$new(data,
                                      y_col = dd,
                                      d_cols = 'rh_adi_bi_0y',
                                      x_cols = dd_features_base, 
                                      z_cols = 'section8_0y')
data_dml_base_iv
  
set.seed(117, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
dml_iivm_ensemble = DoubleMLIIVM$new(data_dml_base_iv,
                                       ml_g = ensemble_pipe_regr,
                                       ml_m = ensemble_pipe_classif,
                                       ml_r = ensemble_pipe_classif,
                                       n_folds = 5)
  
  
dml_iivm_ensemble$tune(param_set = list(
    "ml_g" = space_regr,
    "ml_m" = space_classif,
    "ml_r" = space_classif),
    tune_settings = tune_settings)
  
  
dml_iivm_ensemble$fit()
print(dml_iivm_ensemble$summary())
  
iivm<-as.data.frame(cbind(dml_iivm_ensemble$summary(), dml_iivm_ensemble$confint()))
write.xlsx(iivm, paste0("C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\Double ML IIVM ", dd, " Results_new.xlsx"), asTable = TRUE, rowNames=TRUE)
  
  
  
for (y in ple) {
  data_dml_base_iv = DoubleMLData$new(data,
                                      y_col = y,
                                      d_cols = 'rh_adi_bi_0y',
                                      x_cols = ple_features_base, 
                                      z_cols = 'section8_0y')
  data_dml_base_iv
  
  set.seed(117, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
  dml_iivm_ensemble = DoubleMLIIVM$new(data_dml_base_iv,
                                       ml_g = ensemble_pipe_regr,
                                       ml_m = ensemble_pipe_classif,
                                       ml_r = ensemble_pipe_classif,
                                       n_folds = 5)
  
  
  dml_iivm_ensemble$tune(param_set = list(
    "ml_g" = space_regr,
    "ml_m" = space_classif,
    "ml_r" = space_classif),
    tune_settings = tune_settings)
  
  
  dml_iivm_ensemble$fit()
  print(dml_iivm_ensemble$summary())
  
  iivm<-as.data.frame(cbind(dml_iivm_ensemble$summary(), dml_iivm_ensemble$confint()))
  write.xlsx(iivm, paste0("C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\Double ML IIVM ", y, " Results_new.xlsx"), asTable = TRUE, rowNames=TRUE)
  
}




# p<-c(0.0232241154456845, 0.00434016835520737, 0.00164897459236768, 0.0214074816070311, 0.0051289590994752, 
# 0.0173074527831114, 0.00148500378540409, 0.00149996877916495, 0.193752529407312, 0.0012696607923777)


p_fdr<-as.data.frame(p.adjust(as.matrix(p), method = "fdr"))
rownames(p_fdr)<-outcomes

library(openxlsx)
write.xlsx(p_fdr, file = "C:\\Users\\socra\\Desktop\\Brain discounting\\Double ML Results4\\IIVM pval_new.xlsx", rowNames=TRUE)

```

